### ISSUE TITLE
enable secure access to all pages

### ISSUE THREAD

**Issue by sanjan** [app-generator/django-berry-dashboard-pro#12]
Hi I just purchased the berry pro , just wondering how do I enable secure access to all pages. (ie: I dont want to see the dashboard without logging in) by the way I'm a newbie when it comes to django. but not so when it comes to python.

**Comment by app-generator** [comment]
Hello @sanjan 

Thank you for using [Django Berry PRO](https://appseed.us/product/berry-dashboard-pro/django/)!

To force users to sign in before accessing the private pages you need to edit the [home/views.py](https://github.com/app-generator/django-berry-dashboard-pro/blob/main/home/views.py) as below.

Basically, add the `login_required` decorator to each route you want to protect. 

We'll keep this issue open and wait for your feedback. 

```python
# File: home/views.py 

from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required  # <-- NEW

# Create your views here.

@login_required(login_url='/accounts/login-v1/')           # <-- NEW
def index(request):

    # Page from the theme 
    return render(request, 'pages/index.html')
```

**Comment by sanjan** [comment]
Thanks. that did the trick
